export const state = {
  currentPage: "dashboard",
  transactions: [
    {
      id: 1,
      name: "Supermarché Leclerc",
      category: "nourriture",
      date: "12 Mai, 2024",
      amount: -84.5,
      icon: "🛒",
    },
    {
      id: 2,
      name: "Netflix Subscription",
      category: "loisirs",
      date: "10 Mai, 2024",
      amount: -17.99,
      icon: "🎬",
    },
    {
      id: 3,
      name: "Salaire Mensuel",
      category: "revenu",
      date: "01 Mai, 2024",
      amount: 4250.0,
      icon: "💰",
    },
    {
      id: 4,
      name: "Loyer Appartement",
      category: "logement",
      date: "01 Mai, 2024",
      amount: -1400.0,
      icon: "🏠",
    },
  ],
  budgets: [
    {
      name: "Budget Nourriture",
      total: 500,
      spent: 375,
      colorClass: "fill-green",
      pctClass: "pct-normal",
      label: "75% utilisé",
      restLabel: "Reste: $125.00",
    },
    {
      name: "Budget Loisirs",
      total: 200,
      spent: 190,
      colorClass: "fill-red",
      pctClass: "pct-warning",
      label: "95% utilisé",
      restLabel: "Attention: Presque dépassé",
      restWarning: true,
    },
    {
      name: "Budget Transport",
      total: 150,
      spent: 45,
      colorClass: "fill-blue",
      pctClass: "pct-ok",
      label: "30% utilisé",
      restLabel: "Reste: $105.00",
    },
  ],
  donut: [
    { label: "Loyer", pct: 45, color: "#1d4ed8" },
    { label: "Nourriture", pct: 25, color: "#22c55e" },
    { label: "Loisirs", pct: 30, color: "#a16207" },
  ],
};
